sudo: required
language: python
dist: xenial
cache:
  directories:
  - iverilog

jobs:
    - stage: Tests
      python: 3.7
      before_install:
        - sudo apt-get install gperf
        - if [[ ! -e "./iverilog/README.txt" ]]; then rm -rf iverilog; git clone https://github.com/steveicarus/iverilog.git --depth=1 --branch v10_2; fi
        - cd iverilog && autoconf && ./configure && make -j2 && sudo make install && cd ..
        - pip install tox
        - pyenv global system $TRAVIS_PYTHON_VERSION
      script:
        - tox -e py3
